// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7xfqTrCKnwC_PCW5kqT972TUbYJHRpc',
    appId: '1:1081899432375:web:345ffa2bac8bbcb04cd032',
    messagingSenderId: '1081899432375',
    projectId: 'tracelapp',
    authDomain: 'tracelapp.firebaseapp.com',
    storageBucket: 'tracelapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3UmkN2etKz_POn40-YsV3HF60vXSymZY',
    appId: '1:1081899432375:android:16f2bd0108f6ee524cd032',
    messagingSenderId: '1081899432375',
    projectId: 'tracelapp',
    storageBucket: 'tracelapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgR-vzFHLg1hhMdiskxl6Q8V2JkFIN6FE',
    appId: '1:1081899432375:ios:fd8a3556afd916114cd032',
    messagingSenderId: '1081899432375',
    projectId: 'tracelapp',
    storageBucket: 'tracelapp.appspot.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgR-vzFHLg1hhMdiskxl6Q8V2JkFIN6FE',
    appId: '1:1081899432375:ios:bc90ddabbc8613a54cd032',
    messagingSenderId: '1081899432375',
    projectId: 'tracelapp',
    storageBucket: 'tracelapp.appspot.com',
    iosBundleId: 'com.example.travelapp.RunnerTests',
  );
}
